import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    "introduction"
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    }
  ]
};

export default sidebars;
