import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated', 
      dirName: 'zuord'
    }
  ],
  api: [
    {
      type: 'autogenerated', 
      dirName: 'api'
    }
  ],
  util: [
    {
      type: 'autogenerated',
      dirName: 'util'
    }
  ]
};

export default sidebars;
